- include: users.yml
- include: private_keys.yml

- name: setup ./ssh/config
  template:
    dest: "{{ '/' if item.user == 'root' else '/home' }}/{{ item.user }}/.ssh/config"
    group: "{{ item.user }}"
    mode: 0600
    owner: "{{ item.user }}"
    src: config.j2
  # no_log: True
  when: item.ssh_configs is defined
  with_items: "{{ authorized_users }}"
